// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/15/2026, 9:21:18 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/User/OneDrive/Documents/Yolaab/Frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/OneDrive/Documents/Yolaab/Frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/OneDrive/Documents/Yolaab/Frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/OneDrive/Documents/Yolaab/Frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/OneDrive/Documents/Yolaab/Frontend/plugins/**/*.{js,ts,mjs}","C:/Users/User/OneDrive/Documents/Yolaab/Frontend/composables/**/*.{js,ts,mjs}","C:/Users/User/OneDrive/Documents/Yolaab/Frontend/utils/**/*.{js,ts,mjs}","C:/Users/User/OneDrive/Documents/Yolaab/Frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/OneDrive/Documents/Yolaab/Frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/OneDrive/Documents/Yolaab/Frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/OneDrive/Documents/Yolaab/Frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;